### ISSUE TITLE
Typescript project won't compile with Jovo 2.0.16

### ISSUE THREAD

**Issue by mderrien29** [jovotech/jovo-framework#391]
## I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Other... Please describe:

## Expected Behavior
Compiling.

## Current Behavior
Not compiling.

The issue is probably related to the bug I reported on discord earlier this week about some small inconsistencies in the return type of `this.$cms.t()`.

### Error log
```
intents/passeport.ts:480:16 - error TS2345: Argument of type 'string | object | string[] | object[]' is not assignable to parameter of type 'string | SpeechBuilder'.
  Type 'object' is not assignable to type 'string | SpeechBuilder'.
    Type 'object' is not assignable to type 'SpeechBuilder'.

this.ask(this.$cms.t('fallback'));
```

## Your Environment
* CMS : Jovo Google Sheets
* Jovo Framework version used: 2.0.16
* Typescript: 3.3.3333
* Operating System: docker container based on node:11

**Comment by aswetlow** [comment]
Yeah, you're right. We may revert the last commit or find a better solution.

A quick workaround for now: `this.ask(this.$cms.t('fallback').toString());`

**Comment by aswetlow** [comment]
Fixed in 2.1
